### ISSUE TITLE
i'm too weak 

### ISSUE THREAD

**Issue by amit-xai** [m3f157O/combine_harvester#1]
I have ran exe as admin but still error ,

what kind of priv it does require

**Comment by m3f157O** [comment]
For cli and GUI, run as Administrator.

Maybe you have RunAsPPL or CredentialGuard?

What AV/EDR are you running?

**Comment by amit-xai** [comment]
I am running as Administrator also tried with NT Authority, 
I am on TrendMicro EDR , i believe i dont have Credential Guard but still i Will check

**Comment by m3f157O** [comment]
Thanks for reporting this, I will try it myself as well. It is possible that solutions are starting to learn its behavior, that would be my purpose. The last time I tried (~15 days ago with the free trial version) I didn't have any issues.

Kaspersky was the only one Im aware of which is able to detect it from the start.

Microsoft EDR is starting to pick it up (critical alert but no prevention yet)

**Comment by kalinavladd** [comment]
Hello. I am a beginner, but I am very interested in the topic of security. And I'm also trying to code rust. I'm trying to develop my own small project (its dropper with any functions), but so far my knowledge is very small. May I ask for a couple of tips. Perhaps you have a discord or telegram or email. I would also like to see the complete application code. Because earlier on rust I was engaged in web development. And development for windows is very similar to C, which I don't know( 
Thx.

**Comment by m3f157O** [comment]
@amit-sec I'll get back to you tomorrow. A friend has confirmed that it is not detected by TrendMicro but the dump is not possible

@kalinavladd write to me on telegram @m3f1570
I'm not a pro rust developer, I started 4 months ago. But if you have questions I'll try to answer you

**Comment by M3F1570** [comment]
> @amit-sec I'll get back to you tomorrow. A friend has confirmed that it is not detected by TrendMicro but the dump is not possible
> 
> @kalinavladd write to me on telegram @m3f1570
> I'm not a pro rust developer, I started 4 months ago. But if you have questions I'll try to answer you  

You tagged the wrong person ;)

@M3F157O @M3F1570

**Comment by m3f157O** [comment]
Sorry that is my telegram username 😂😂😂 I didnt think about the git tag. Have a nice one bro

**Comment by amit-xai** [comment]
as of now trendmicro edr is not detecting it as malicious but still dump is not working , i have tried disabling Credential Guard , i believe its runasppl causing issue

**Comment by m3f157O** [comment]
You can send me the details in private on telegram @ m3f1570
